import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import MenuButtons from "../components/route_component/menu_buttons";
import ModalComponent from "../components/route_component/modalComponent";
import SideModels from "../components/route_component/side_models";
import Header from "../components/route_component/header";
import SideBar from "../components/route_component/sidebar";
import Provider from "../utils/sessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "../utils/auth";
import { redirect } from "next/navigation";
import { Toaster } from "react-hot-toast";

const font = Inter({ subsets: ["cyrillic", "cyrillic-ext", "greek", "greek-ext", "latin", "latin-ext"], display: "swap", adjustFontFallback: true });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  if (!session) return redirect("/login")
  return (
    <html lang="en">
      <body className={font.className}>
        <Toaster />
        <Provider session={session}>
          <div className="relative grid min-h-screen lg:grid-cols-9">
            <div className="col-span-2">
              <SideBar />
            </div>
            <div className="col-span-7 overflow-auto border-r">
              <Header />
              <div className="grid min-h-screen lg:grid-cols-7 ">
                <div className="col-span-4 md:border-r">
                  {children}
                </div>
                <SideModels />
              </div>
            </div>
            <MenuButtons />
            <ModalComponent />
          </div>
        </Provider>
      </body>
    </html>
  );
}
